// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/metadata/interface.go

// Package metadata is a generated GoMock package.
package metadata

import (
	context "context"

	arn "github.com/aws/aws-sdk-go-v2/aws/arn"
	imds "github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
	gomock "github.com/golang/mock/gomock"
)

// MockMetadataService is a mock of MetadataService interface.
type MockMetadataService struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataServiceMockRecorder
}

// MockMetadataServiceMockRecorder is the mock recorder for MockMetadataService.
type MockMetadataServiceMockRecorder struct {
	mock *MockMetadataService
}

// NewMockMetadataService creates a new mock instance.
func NewMockMetadataService(ctrl *gomock.Controller) *MockMetadataService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataService) EXPECT() *MockMetadataServiceMockRecorder {
	_ = "STUB: not implemented"

	// GetAvailabilityZone mocks base method.
	return nil
}

func (m *MockMetadataService) GetAvailabilityZone() string { _ = "STUB: not implemented"; return "" }

// GetAvailabilityZone indicates an expected call of GetAvailabilityZone.
func (mr *MockMetadataServiceMockRecorder) GetAvailabilityZone() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInstanceID mocks base method.
func (m *MockMetadataService) GetInstanceID() string { _ = "STUB: not implemented"; return "" }

// GetInstanceID indicates an expected call of GetInstanceID.
func (mr *MockMetadataServiceMockRecorder) GetInstanceID() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInstanceType mocks base method.
func (m *MockMetadataService) GetInstanceType() string { _ = "STUB: not implemented"; return "" }

// GetInstanceType indicates an expected call of GetInstanceType.
func (mr *MockMetadataServiceMockRecorder) GetInstanceType() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNumAttachedENIs mocks base method.
func (m *MockMetadataService) GetNumAttachedENIs() int { _ = "STUB: not implemented"; return 0 }

// GetNumAttachedENIs indicates an expected call of GetNumAttachedENIs.
func (mr *MockMetadataServiceMockRecorder) GetNumAttachedENIs() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNumBlockDeviceMappings mocks base method.
func (m *MockMetadataService) GetNumBlockDeviceMappings() int { _ = "STUB: not implemented"; return 0 }

// GetNumBlockDeviceMappings indicates an expected call of GetNumBlockDeviceMappings.
func (mr *MockMetadataServiceMockRecorder) GetNumBlockDeviceMappings() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOutpostArn mocks base method.
func (m *MockMetadataService) GetOutpostArn() arn.ARN {
	_ = "STUB: not implemented"
	return *new(arn.ARN)
}

// GetOutpostArn indicates an expected call of GetOutpostArn.
func (mr *MockMetadataServiceMockRecorder) GetOutpostArn() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRegion mocks base method.
func (m *MockMetadataService) GetRegion() string { _ = "STUB: not implemented"; return "" }

// GetRegion indicates an expected call of GetRegion.
func (mr *MockMetadataServiceMockRecorder) GetRegion() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateMetadata mocks base method.
func (m *MockMetadataService) UpdateMetadata() error { _ = "STUB: not implemented"; return nil }

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockMetadataServiceMockRecorder) UpdateMetadata() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockIMDS is a mock of IMDS interface.
type MockIMDS struct {
	ctrl     *gomock.Controller
	recorder *MockIMDSMockRecorder
}

// MockIMDSMockRecorder is the mock recorder for MockIMDS.
type MockIMDSMockRecorder struct {
	mock *MockIMDS
}

// NewMockIMDS creates a new mock instance.
func NewMockIMDS(ctrl *gomock.Controller) *MockIMDS { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMDS) EXPECT() *MockIMDSMockRecorder {
	_ = "STUB: not implemented"

	// GetDynamicData mocks base method.
	return nil
}

func (m *MockIMDS) GetDynamicData(ctx context.Context, params *imds.GetDynamicDataInput, optFns ...func(*imds.Options)) (*imds.GetDynamicDataOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDynamicData indicates an expected call of GetDynamicData.
func (mr *MockIMDSMockRecorder) GetDynamicData(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetIAMInfo mocks base method.
func (m *MockIMDS) GetIAMInfo(ctx context.Context, params *imds.GetIAMInfoInput, optFns ...func(*imds.Options)) (*imds.GetIAMInfoOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetIAMInfo indicates an expected call of GetIAMInfo.
func (mr *MockIMDSMockRecorder) GetIAMInfo(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInstanceIdentityDocument mocks base method.
func (m *MockIMDS) GetInstanceIdentityDocument(ctx context.Context, params *imds.GetInstanceIdentityDocumentInput, optFns ...func(*imds.Options)) (*imds.GetInstanceIdentityDocumentOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInstanceIdentityDocument indicates an expected call of GetInstanceIdentityDocument.
func (mr *MockIMDSMockRecorder) GetInstanceIdentityDocument(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMetadata mocks base method.
func (m *MockIMDS) GetMetadata(ctx context.Context, params *imds.GetMetadataInput, optFns ...func(*imds.Options)) (*imds.GetMetadataOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockIMDSMockRecorder) GetMetadata(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRegion mocks base method.
func (m *MockIMDS) GetRegion(ctx context.Context, params *imds.GetRegionInput, optFns ...func(*imds.Options)) (*imds.GetRegionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockIMDSMockRecorder) GetRegion(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserData mocks base method.
func (m *MockIMDS) GetUserData(ctx context.Context, params *imds.GetUserDataInput, optFns ...func(*imds.Options)) (*imds.GetUserDataOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserData indicates an expected call of GetUserData.
func (mr *MockIMDSMockRecorder) GetUserData(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
