// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/util/sagemaker_interface.go

// Package cloud is a generated GoMock package.
package cloud

import (
	context "context"

	sagemaker "github.com/aws/aws-sdk-go-v2/service/sagemaker"
	gomock "github.com/golang/mock/gomock"
)

// MockSageMakerAPI is a mock of SageMakerAPI interface.
type MockSageMakerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSageMakerAPIMockRecorder
}

// MockSageMakerAPIMockRecorder is the mock recorder for MockSageMakerAPI.
type MockSageMakerAPIMockRecorder struct {
	mock *MockSageMakerAPI
}

// NewMockSageMakerAPI creates a new mock instance.
func NewMockSageMakerAPI(ctrl *gomock.Controller) *MockSageMakerAPI {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSageMakerAPI) EXPECT() *MockSageMakerAPIMockRecorder {
	_ = "STUB: not implemented"

	// AttachClusterNodeVolume mocks base method.
	return nil
}

func (m *MockSageMakerAPI) AttachClusterNodeVolume(ctx context.Context, params *sagemaker.AttachClusterNodeVolumeInput, optFns ...func(*sagemaker.Options)) (*sagemaker.AttachClusterNodeVolumeOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AttachClusterNodeVolume indicates an expected call of AttachClusterNodeVolume.
func (mr *MockSageMakerAPIMockRecorder) AttachClusterNodeVolume(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DetachClusterNodeVolume mocks base method.
func (m *MockSageMakerAPI) DetachClusterNodeVolume(ctx context.Context, params *sagemaker.DetachClusterNodeVolumeInput, optFns ...func(*sagemaker.Options)) (*sagemaker.DetachClusterNodeVolumeOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DetachClusterNodeVolume indicates an expected call of DetachClusterNodeVolume.
func (mr *MockSageMakerAPIMockRecorder) DetachClusterNodeVolume(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
