// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/interface.go

// Package cloud is a generated GoMock package.
package cloud

import (
	context "context"

	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	gomock "github.com/golang/mock/gomock"
)

// MockCloud is a mock of Cloud interface.
type MockCloud struct {
	ctrl     *gomock.Controller
	recorder *MockCloudMockRecorder
}

// MockCloudMockRecorder is the mock recorder for MockCloud.
type MockCloudMockRecorder struct {
	mock *MockCloud
}

// NewMockCloud creates a new mock instance.
func NewMockCloud(ctrl *gomock.Controller) *MockCloud { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloud) EXPECT() *MockCloudMockRecorder {
	_ = "STUB: not implemented"

	// AttachDisk mocks base method.
	return nil
}

func (m *MockCloud) AttachDisk(ctx context.Context, volumeID, nodeID string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// AttachDisk indicates an expected call of AttachDisk.
func (mr *MockCloudMockRecorder) AttachDisk(ctx, volumeID, nodeID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AvailabilityZones mocks base method.
func (m *MockCloud) AvailabilityZones(ctx context.Context) (map[string]struct{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AvailabilityZones indicates an expected call of AvailabilityZones.
func (mr *MockCloudMockRecorder) AvailabilityZones(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateDisk mocks base method.
func (m *MockCloud) CreateDisk(ctx context.Context, volumeName string, diskOptions *DiskOptions) (*Disk, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateDisk indicates an expected call of CreateDisk.
func (mr *MockCloudMockRecorder) CreateDisk(ctx, volumeName, diskOptions interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSnapshot mocks base method.
func (m *MockCloud) CreateSnapshot(ctx context.Context, volumeID string, snapshotOptions *SnapshotOptions) (*Snapshot, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockCloudMockRecorder) CreateSnapshot(ctx, volumeID, snapshotOptions interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteDisk mocks base method.
func (m *MockCloud) DeleteDisk(ctx context.Context, volumeID string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// DeleteDisk indicates an expected call of DeleteDisk.
func (mr *MockCloudMockRecorder) DeleteDisk(ctx, volumeID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSnapshot mocks base method.
func (m *MockCloud) DeleteSnapshot(ctx context.Context, snapshotID string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockCloudMockRecorder) DeleteSnapshot(ctx, snapshotID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DetachDisk mocks base method.
func (m *MockCloud) DetachDisk(ctx context.Context, volumeID, nodeID string) error {
	_ = "STUB: not implemented"
	return nil
}

// DetachDisk indicates an expected call of DetachDisk.
func (mr *MockCloudMockRecorder) DetachDisk(ctx, volumeID, nodeID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DryRun mocks base method.
func (m *MockCloud) DryRun(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// DryRun indicates an expected call of DryRun.
func (mr *MockCloudMockRecorder) DryRun(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EnableFastSnapshotRestores mocks base method.
func (m *MockCloud) EnableFastSnapshotRestores(ctx context.Context, availabilityZones []string, snapshotID string) (*ec2.EnableFastSnapshotRestoresOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnableFastSnapshotRestores indicates an expected call of EnableFastSnapshotRestores.
func (mr *MockCloudMockRecorder) EnableFastSnapshotRestores(ctx, availabilityZones, snapshotID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDiskByID mocks base method.
func (m *MockCloud) GetDiskByID(ctx context.Context, volumeID string) (*Disk, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDiskByID indicates an expected call of GetDiskByID.
func (mr *MockCloudMockRecorder) GetDiskByID(ctx, volumeID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDiskByName mocks base method.
func (m *MockCloud) GetDiskByName(ctx context.Context, name string, capacityBytes int64) (*Disk, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDiskByName indicates an expected call of GetDiskByName.
func (mr *MockCloudMockRecorder) GetDiskByName(ctx, name, capacityBytes interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInstancesPatching mocks base method.
func (m *MockCloud) GetInstancesPatching(ctx context.Context, nodeIDs []string) ([]*types.Instance, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInstancesPatching indicates an expected call of GetInstancesPatching.
func (mr *MockCloudMockRecorder) GetInstancesPatching(ctx, nodeIDs interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSnapshotByID mocks base method.
func (m *MockCloud) GetSnapshotByID(ctx context.Context, snapshotID string) (*Snapshot, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSnapshotByID indicates an expected call of GetSnapshotByID.
func (mr *MockCloudMockRecorder) GetSnapshotByID(ctx, snapshotID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSnapshotByName mocks base method.
func (m *MockCloud) GetSnapshotByName(ctx context.Context, name string) (*Snapshot, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSnapshotByName indicates an expected call of GetSnapshotByName.
func (mr *MockCloudMockRecorder) GetSnapshotByName(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVolumeIDByNodeAndDevice mocks base method.
func (m *MockCloud) GetVolumeIDByNodeAndDevice(ctx context.Context, nodeID, deviceName string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetVolumeIDByNodeAndDevice indicates an expected call of GetVolumeIDByNodeAndDevice.
func (mr *MockCloudMockRecorder) GetVolumeIDByNodeAndDevice(ctx, nodeID, deviceName interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsVolumeInitialized mocks base method.
func (m *MockCloud) IsVolumeInitialized(ctx context.Context, volumeID string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsVolumeInitialized indicates an expected call of IsVolumeInitialized.
func (mr *MockCloudMockRecorder) IsVolumeInitialized(ctx, volumeID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSnapshots mocks base method.
func (m *MockCloud) ListSnapshots(ctx context.Context, volumeID string, maxResults int32, nextToken string) (*ListSnapshotsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockCloudMockRecorder) ListSnapshots(ctx, volumeID, maxResults, nextToken interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LockSnapshot mocks base method.
func (m *MockCloud) LockSnapshot(ctx context.Context, lockOptions *SnapshotLockOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// LockSnapshot indicates an expected call of LockSnapshot.
func (mr *MockCloudMockRecorder) LockSnapshot(ctx, lockOptions interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ModifyTags mocks base method.
func (m *MockCloud) ModifyTags(ctx context.Context, volumeID string, tagOptions ModifyTagsOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ModifyTags indicates an expected call of ModifyTags.
func (mr *MockCloudMockRecorder) ModifyTags(ctx, volumeID, tagOptions interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResizeOrModifyDisk mocks base method.
func (m *MockCloud) ResizeOrModifyDisk(ctx context.Context, volumeID string, newSizeBytes int64, options *ModifyDiskOptions) (int32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ResizeOrModifyDisk indicates an expected call of ResizeOrModifyDisk.
func (mr *MockCloudMockRecorder) ResizeOrModifyDisk(ctx, volumeID, newSizeBytes, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForAttachmentState mocks base method.
func (m *MockCloud) WaitForAttachmentState(ctx context.Context, expectedState types.VolumeAttachmentState, volumeID, expectedInstance, expectedDevice string, alreadyAssigned bool, expectedCardIndex *int32) (*types.VolumeAttachment, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WaitForAttachmentState indicates an expected call of WaitForAttachmentState.
func (mr *MockCloudMockRecorder) WaitForAttachmentState(ctx, expectedState, volumeID, expectedInstance, expectedDevice, alreadyAssigned, expectedCardIndex interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
