// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/mounter/mount.go

// Package mounter is a generated GoMock package.
package mounter

import (
	gomock "github.com/golang/mock/gomock"
	mount_utils "k8s.io/mount-utils"
)

// MockMounter is a mock of Mounter interface.
type MockMounter struct {
	ctrl     *gomock.Controller
	recorder *MockMounterMockRecorder
}

// MockMounterMockRecorder is the mock recorder for MockMounter.
type MockMounterMockRecorder struct {
	mock *MockMounter
}

// NewMockMounter creates a new mock instance.
func NewMockMounter(ctrl *gomock.Controller) *MockMounter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMounter) EXPECT() *MockMounterMockRecorder {
	_ = "STUB: not implemented"

	// CanSafelySkipMountPointCheck mocks base method.
	return nil
}

func (m *MockMounter) CanSafelySkipMountPointCheck() bool { _ = "STUB: not implemented"; return false }

// CanSafelySkipMountPointCheck indicates an expected call of CanSafelySkipMountPointCheck.
func (mr *MockMounterMockRecorder) CanSafelySkipMountPointCheck() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FindDevicePath mocks base method.
func (m *MockMounter) FindDevicePath(devicePath, volumeID, partition, region string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// FindDevicePath indicates an expected call of FindDevicePath.
func (mr *MockMounterMockRecorder) FindDevicePath(devicePath, volumeID, partition, region interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FormatAndMountSensitiveWithFormatOptions mocks base method.
func (m *MockMounter) FormatAndMountSensitiveWithFormatOptions(source, target, fstype string, options, sensitiveOptions, formatOptions []string) error {
	_ = "STUB: not implemented"
	return nil
}

// FormatAndMountSensitiveWithFormatOptions indicates an expected call of FormatAndMountSensitiveWithFormatOptions.
func (mr *MockMounterMockRecorder) FormatAndMountSensitiveWithFormatOptions(source, target, fstype, options, sensitiveOptions, formatOptions interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlockSizeBytes mocks base method.
func (m *MockMounter) GetBlockSizeBytes(devicePath string) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetBlockSizeBytes indicates an expected call of GetBlockSizeBytes.
func (mr *MockMounterMockRecorder) GetBlockSizeBytes(devicePath interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDeviceNameFromMount mocks base method.
func (m *MockMounter) GetDeviceNameFromMount(mountPath string) (string, int, error) {
	_ = "STUB: not implemented"
	return "", 0, nil
}

// GetDeviceNameFromMount indicates an expected call of GetDeviceNameFromMount.
func (mr *MockMounterMockRecorder) GetDeviceNameFromMount(mountPath interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMountRefs mocks base method.
func (m *MockMounter) GetMountRefs(pathname string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMountRefs indicates an expected call of GetMountRefs.
func (mr *MockMounterMockRecorder) GetMountRefs(pathname interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVolumeStats mocks base method.
func (m *MockMounter) GetVolumeStats(volumePath string) (VolumeStats, error) {
	_ = "STUB: not implemented"
	return *new(VolumeStats), nil
}

// GetVolumeStats indicates an expected call of GetVolumeStats.
func (mr *MockMounterMockRecorder) GetVolumeStats(volumePath interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsBlockDevice mocks base method.
func (m *MockMounter) IsBlockDevice(fullPath string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsBlockDevice indicates an expected call of IsBlockDevice.
func (mr *MockMounterMockRecorder) IsBlockDevice(fullPath interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsCorruptedMnt mocks base method.
func (m *MockMounter) IsCorruptedMnt(err error) bool { _ = "STUB: not implemented"; return false }

// IsCorruptedMnt indicates an expected call of IsCorruptedMnt.
func (mr *MockMounterMockRecorder) IsCorruptedMnt(err interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsLikelyNotMountPoint mocks base method.
func (m *MockMounter) IsLikelyNotMountPoint(file string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsLikelyNotMountPoint indicates an expected call of IsLikelyNotMountPoint.
func (mr *MockMounterMockRecorder) IsLikelyNotMountPoint(file interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsMountPoint mocks base method.
func (m *MockMounter) IsMountPoint(file string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsMountPoint indicates an expected call of IsMountPoint.
func (mr *MockMounterMockRecorder) IsMountPoint(file interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// List mocks base method.
func (m *MockMounter) List() ([]mount_utils.MountPoint, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List indicates an expected call of List.
func (mr *MockMounterMockRecorder) List() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MakeDir mocks base method.
func (m *MockMounter) MakeDir(path string) error { _ = "STUB: not implemented"; return nil }

// MakeDir indicates an expected call of MakeDir.
func (mr *MockMounterMockRecorder) MakeDir(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MakeFile mocks base method.
func (m *MockMounter) MakeFile(path string) error { _ = "STUB: not implemented"; return nil }

// MakeFile indicates an expected call of MakeFile.
func (mr *MockMounterMockRecorder) MakeFile(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Mount mocks base method.
func (m *MockMounter) Mount(source, target, fstype string, options []string) error {
	_ = "STUB: not implemented"
	return nil
}

// Mount indicates an expected call of Mount.
func (mr *MockMounterMockRecorder) Mount(source, target, fstype, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MountSensitive mocks base method.
func (m *MockMounter) MountSensitive(source, target, fstype string, options, sensitiveOptions []string) error {
	_ = "STUB: not implemented"
	return nil
}

// MountSensitive indicates an expected call of MountSensitive.
func (mr *MockMounterMockRecorder) MountSensitive(source, target, fstype, options, sensitiveOptions interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MountSensitiveWithoutSystemd mocks base method.
func (m *MockMounter) MountSensitiveWithoutSystemd(source, target, fstype string, options, sensitiveOptions []string) error {
	_ = "STUB: not implemented"
	return nil
}

// MountSensitiveWithoutSystemd indicates an expected call of MountSensitiveWithoutSystemd.
func (mr *MockMounterMockRecorder) MountSensitiveWithoutSystemd(source, target, fstype, options, sensitiveOptions interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MountSensitiveWithoutSystemdWithMountFlags mocks base method.
func (m *MockMounter) MountSensitiveWithoutSystemdWithMountFlags(source, target, fstype string, options, sensitiveOptions, mountFlags []string) error {
	_ = "STUB: not implemented"
	return nil
}

// MountSensitiveWithoutSystemdWithMountFlags indicates an expected call of MountSensitiveWithoutSystemdWithMountFlags.
func (mr *MockMounterMockRecorder) MountSensitiveWithoutSystemdWithMountFlags(source, target, fstype, options, sensitiveOptions, mountFlags interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NeedResize mocks base method.
func (m *MockMounter) NeedResize(devicePath, deviceMountPath string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// NeedResize indicates an expected call of NeedResize.
func (mr *MockMounterMockRecorder) NeedResize(devicePath, deviceMountPath interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PathExists mocks base method.
func (m *MockMounter) PathExists(path string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// PathExists indicates an expected call of PathExists.
func (mr *MockMounterMockRecorder) PathExists(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PreparePublishTarget mocks base method.
func (m *MockMounter) PreparePublishTarget(target string) error {
	_ = "STUB: not implemented"
	return nil
}

// PreparePublishTarget indicates an expected call of PreparePublishTarget.
func (mr *MockMounterMockRecorder) PreparePublishTarget(target interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Resize mocks base method.
func (m *MockMounter) Resize(devicePath, deviceMountPath string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Resize indicates an expected call of Resize.
func (mr *MockMounterMockRecorder) Resize(devicePath, deviceMountPath interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unmount mocks base method.
func (m *MockMounter) Unmount(target string) error { _ = "STUB: not implemented"; return nil }

// Unmount indicates an expected call of Unmount.
func (mr *MockMounterMockRecorder) Unmount(target interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unpublish mocks base method.
func (m *MockMounter) Unpublish(path string) error { _ = "STUB: not implemented"; return nil }

// Unpublish indicates an expected call of Unpublish.
func (mr *MockMounterMockRecorder) Unpublish(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unstage mocks base method.
func (m *MockMounter) Unstage(path string) error { _ = "STUB: not implemented"; return nil }

// Unstage indicates an expected call of Unstage.
func (mr *MockMounterMockRecorder) Unstage(path interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
